### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by kastoestoramadus** [rtimush/sbt-updates#79]
I got sbt 0.13.15 and sbt-updates 0.3.2. 
An error is thrown:

>sbt dependencyUpdates
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading project definition from /home/walidus/IdeaProjects/tracking/project
[info] Set current project to tracking (in build file:/home/walidus/IdeaProjects/tracking/)
java.lang.NoSuchMethodError: sbt.ModuleID.withRevision(Ljava/lang/String;)Lsbt/ModuleID;
        at com.timushev.sbt.updates.Reporter$$anonfun$include$1.apply(Reporter.scala:123)
        at com.timushev.sbt.updates.Reporter$$anonfun$include$1.apply(Reporter.scala:123)
        at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
        at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:84)
        at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:83)

According to : http://www.scala-sbt.org/0.13/sxr/sbt/ModuleID.scala.html
there is no such method. It is used from here line 123: https://github.com/rtimush/sbt-updates/blob/3b5109c1c5e04edc36da636a6b73b09a6337710c/src/main/scala/com/timushev/sbt/updates/Reporter.scala .

**Comment by kastoestoramadus** [comment]
Works fine with 0.3.1

**Comment by rtimush** [comment]
Thanks for reporting. While I'm fixing these compatibility issues, you can switch to sbt 0.13.16 — it should work fine.

**Comment by rtimush** [comment]
Fixed in `sbt-updates 0.3.3`
