### PR TITLE
Remove Ivy dependency from update checks

### LINKED ISSUE #9679: [2.x] sbt-updates plugin does not work with sbt 2.1.0-SNAPSHOT
## steps

https://github.com/xuwei-k/sbt/commit/48cb5ceeb4ed149518fcb87d52c05bea24164762

```diff
diff --git a/sbt-app/src/sbt-test/plugins/sbt-updates/project/plugins.sbt b/sbt-app/src/sbt-test/plugins/sbt-updates/project/plugins.sbt
new file mode 100644
index 000000000..c9974f2fc
--- /dev/null
+++ b/sbt-app/src/sbt-test/plugins/sbt-updates/project/plugins.sbt
@@ -0,0 +1 @@
+addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.7.0")
diff --git a/sbt-app/src/sbt-test/plugins/sbt-updates/test b/sbt-app/src/sbt-test/plugins/sbt-updates/test
new file mode 100644
index 000000000..9d8889ea0
--- /dev/null
+++ b/sbt-app/src/sbt-test/plugins/sbt-updates/test
@@ -0,0 +1 @@
+> dependencyUpdates
```

```sh
sbt "scripted plugins/sbt-updates"
```

## problem

```
[info] [error] java.lang.NoClassDefFoundError: org/apache/ivy/core/IvyPatternHelper
[info] [error] 	at com.timushev.sbt.updates.metadata.MavenMetadataLoader.url(MavenMetadataLoader.scala:34)
[info] [error] 	at com.timushev.sbt.updates.metadata.MavenMetadataLoader.getVersions$$anonfun$1(MavenMetadataLoader.scala:20)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap(StrictOptimizedIterableOps.scala:120)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap$(StrictOptimizedIterableOps.scala:29)
[info] [error] 	at scala.collection.immutable.Vector.strictOptimizedFlatMap(Vector.scala:119)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:108)
[info] [error] 	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:29)
[info] [error] 	at scala.collection.immutable.Vector.flatMap(Vector.scala:119)
[info] [error] 	at com.timushev.sbt.updates.metadata.MavenMetadataLoader.getVersions(MavenMetadataLoader.scala:20)
[info] [error] 	at com.timushev.sbt.updates.metadata.CompoundMetadataLoader.getVersions$$anonfun$1(CompoundMetadataLoader.scala:13)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:240)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:238)
[info] [error] 	at com.timushev.sbt.updates.metadata.CompoundMetadataLoader.getVersions(CompoundMetadataLoader.scala:12)
[info] [error] 	at com.timushev.sbt.updates.metadata.CachingMetadataLoader.getVersions$$anonfun$1(CachingMetadataLoader.scala:15)
[info] [error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:475)
[info] [error] 	at com.timushev.sbt.updates.metadata.CachingMetadataLoader.getVersions(CachingMetadataLoader.scala:15)
[info] [error] 	at com.timushev.sbt.updates.UpdatesFinder$.$anonfun$1(UpdatesFinder.scala:18)
[info] [error] 	at scala.collection.immutable.VectorStatics$.mapElems1(Vector.scala:2143)
[info] [error] 	at scala.collection.immutable.Vector1.map(Vector.scala:415)
[info] [error] 	at scala.collection.immutable.Vector1.map(Vector.scala:415)
[info] [error] 	at com.timushev.sbt.updates.UpdatesFinder$.findUpdates(UpdatesFinder.scala:18)
[info] [error] 	at com.timushev.sbt.updates.Reporter$.$anonfun$4$$anonfun$1(Reporter.scala:43)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:240)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:238)
[info] [error] 	at com.timushev.sbt.updates.Reporter$.$anonfun$4(Reporter.scala:43)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:240)
[info] [error] 	at scala.collection.immutable.List.map(List.scala:238)
[info] [error] 	at com.timushev.sbt.updates.Reporter$.dependencyUpdatesData(Reporter.scala:43)
[info] [error] 	at com.timushev.sbt.updates.UpdatesPlugin$.$init$$$anonfun$7(UpdatesPlugin.scala:26)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:79)
```

## notes

- https://github.com/sbt/sbt/pull/9615

https://github.com/rtimush/sbt-updates/blob/6e78a18483295ccfb87bb143d59a5cdd97093623/src/main/scala/com/timushev/sbt/updates/metadata/MavenMetadataLoader.scala#L8C28-L8C44

sbt-updates plugin use apache ivy classes

```
$ git grep org.apache.ivy
src/main/scala/com/timushev/sbt/updates/Downloader.scala:4:import org.apache.ivy.Ivy
src/main/scala/com/timushev/sbt/updates/Downloader.scala:14:    // Same as in org.apache.ivy.util.url.BasicURLHandler
src/main/scala/com/timushev/sbt/updates/metadata/IvyMetadataLoader.scala:10:import org.apache.ivy.core.IvyPatternHelper
src/main/scala/com/timushev/sbt/updates/metadata/MavenMetadataLoader.scala:8:import org.apache.ivy.core.IvyPatternHelper
```

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
Fixes sbt/sbt#9679.

`dependencyUpdates` crashes on sbt 2.1.0-SNAPSHOT because sbt-updates uses Ivy classes that sbt no longer supplies after sbt/sbt#9615. Replace Ivy's repository-pattern substitution and revision-prefix extraction with a shared private helper used by both metadata loaders. Also use a plugin-specific HTTP user agent instead of querying Ivy's version.

Validation:
- New unit tests test the correctness of repository pattern-substitution and revision-prefix extraction. They cover revision prefixes, optional sections, extra attributes, malformed patterns, metadata URLs/version extraction, and HTTP headers/authentication.
- Locally, `updates/auto` fails without the fix with `NoClassDefFoundError: org/apache/ivy/core/IvyPatternHelper` and passes with it on the same freshly published sbt 2.1.0-SNAPSHOT using an isolated Ivy-free boot directory.

### CODE REVIEW

**Comment by rtimush** [comment]
Thank you, @anatoliykmetyuk
